In [1]:
import numpy as np
from WCST import WcstSession

In [20]:
session = WcstSession(num_cards=4, num_dims=3, trials_to_crit1=[2,2], trials_to_crit2=None)

In [21]:
session.current_rule

5

In [22]:
session.get_cards()

array([[ 2,  4,  8],
       [ 3,  5, 10],
       [ 0,  6, 11],
       [ 1,  7,  9]])

In [23]:
session.make_selection(0)

False

In [24]:
session.current_rule

5

In [25]:
session.get_cards()

array([[ 3,  4,  9],
       [ 1,  5, 10],
       [ 0,  6, 11],
       [ 2,  7,  8]])

In [26]:
session.make_selection(1)

True

In [27]:
session.current_rule

5

In [28]:
session.get_cards()

array([[ 1,  4,  8],
       [ 2,  7, 10],
       [ 0,  6, 11],
       [ 3,  5,  9]])

In [29]:
session.make_selection(3)

True

In [30]:
session.current_rule

10

In [32]:
session.get_cards()

array([[ 1,  5,  8],
       [ 2,  4, 10],
       [ 3,  6, 11],
       [ 0,  7,  9]])

In [33]:
session.make_selection(0)

False

In [34]:
session.dump_history()

TrialNumber  BlockNumber  TrialAfterRuleChange   Response  ItemChosen  \
0            0            0                     0  Incorrect           0   
1            1            0                     1    Correct           1   
2            2            0                     2    Correct           3   
3            3            1                     0  Incorrect           0   

   CurrentRule  Item0 Dim0  Item0 Dim1  Item0 Dim2  Item1 Dim0  Item1 Dim1  \
0            5           2           4           8           3           5   
1            5           3           4           9           1           5   
2            5           1           4           8           2           7   
3           10           1           5           8           2           4   

   Item1 Dim2  Item2 Dim0  Item2 Dim1  Item2 Dim2  Item3 Dim0  Item3 Dim1  \
0          10           0           6          11           1           7   
1          10           0           6          11           2           7   
2          10           0           6          11           3           5   
3          10           3           6          11           0           7   

   Item3 Dim2  
0           9  
1           8  
2           9  
3           9